[package]
name = "constello"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.4", default-features = false, features = ["macros"] }
actix-files = "0.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
diesel = { version = "2.1", features = ["r2d2", "chrono", "sqlite", "returning_clauses_for_sqlite_3_35"] }
diesel_migrations = "2.1"
libsqlite3-sys = { version = ">=0.17.2, <0.26.0", features = ["bundled_bindings", "bundled"] }
once_cell = "1.17"
toml = "0.7"
chrono = { version = "0.4", features = ["serde"], default-features = false }
rand = "0.8"
lettre = "0.11"

